name: FF14 Risingstone Sign Tasks
author: StarHeartHunt <starheart233@gmail.com>
description: auto finish sign tasks of ff14 risingstone
inputs:
  cookie:
    description: The cookie dumped from risingstone web frontend
    required: true
  base_url:
    description: The API domain of risingstone
    required: false
  user_agent:
    description: The user agent to use for requests
    required: false
  comment_content:
    description: The html content of the comment
    required: false
  like_post_id:
    description: The post id to send like
    required: false
  comment_post_id:
    description: The post id to send comment
    required: false

runs:
  using: docker
  image: Dockerfile
branding:
  icon: box
  color: orange
